---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-x-mapping-servicebinding-io-v1alpha1-externalsecretmapping
  failurePolicy: Fail
  name: veso.xmapping.servicebinding.kb.io
  rules:
  - apiGroups:
    - x-mapping.servicebinding.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - externalsecretmappings
  sideEffects: None
