# permissions for end users to view externalsecretmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsecretmapping-viewer-role
rules:
- apiGroups:
  - x-mapping.servicebinding.io
  resources:
  - externalsecretmappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - x-mapping.servicebinding.io
  resources:
  - externalsecretmapping/status
  verbs:
  - get
