# permissions for end users to edit externalsecretmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsecretmapping-editor-role
rules:
- apiGroups:
  - x-mapping.servicebinding.io
  resources:
  - externalsecretmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - x-mapping.servicebinding.io
  resources:
  - externalsecretmappings/status
  verbs:
  - get
