//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"
	fmtx "fmt"

	v1 "dies.dev/apis/meta/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"

	"github.com/servicebinding/mapping-externalsecrets/apis/v1alpha1"
)

var ExternalSecretMappingBlank = (&ExternalSecretMappingDie{}).DieFeed(v1alpha1.ExternalSecretMapping{})

type ExternalSecretMappingDie struct {
	v1.FrozenObjectMeta
	mutable bool
	r       v1alpha1.ExternalSecretMapping
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ExternalSecretMappingDie) DieImmutable(immutable bool) *ExternalSecretMappingDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ExternalSecretMappingDie) DieFeed(r v1alpha1.ExternalSecretMapping) *ExternalSecretMappingDie {
	if d.mutable {
		d.FrozenObjectMeta = v1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &ExternalSecretMappingDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ExternalSecretMappingDie) DieFeedPtr(r *v1alpha1.ExternalSecretMapping) *ExternalSecretMappingDie {
	if r == nil {
		r = &v1alpha1.ExternalSecretMapping{}
	}
	return d.DieFeed(*r)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension.
func (d *ExternalSecretMappingDie) DieFeedRawExtension(raw runtime.RawExtension) *ExternalSecretMappingDie {
	b, _ := json.Marshal(raw)
	r := v1alpha1.ExternalSecretMapping{}
	_ = json.Unmarshal(b, &r)
	return d.DieFeed(r)
}

// DieRelease returns the resource managed by the die.
func (d *ExternalSecretMappingDie) DieRelease() v1alpha1.ExternalSecretMapping {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ExternalSecretMappingDie) DieReleasePtr() *v1alpha1.ExternalSecretMapping {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object.
func (d *ExternalSecretMappingDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, _ := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension.
func (d *ExternalSecretMappingDie) DieReleaseRawExtension() runtime.RawExtension {
	r := d.DieReleasePtr()
	b, _ := json.Marshal(r)
	raw := runtime.RawExtension{}
	_ = json.Unmarshal(b, &raw)
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ExternalSecretMappingDie) DieStamp(fn func(r *v1alpha1.ExternalSecretMapping)) *ExternalSecretMappingDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ExternalSecretMappingDie) DeepCopy() *ExternalSecretMappingDie {
	r := *d.r.DeepCopy()
	return &ExternalSecretMappingDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*ExternalSecretMappingDie)(nil)

func (d *ExternalSecretMappingDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *ExternalSecretMappingDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *ExternalSecretMappingDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *ExternalSecretMappingDie) UnmarshalJSON(b []byte) error {
	if d == ExternalSecretMappingBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &v1alpha1.ExternalSecretMapping{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *ExternalSecretMappingDie) APIVersion(v string) *ExternalSecretMappingDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMapping) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *ExternalSecretMappingDie) Kind(v string) *ExternalSecretMappingDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMapping) {
		r.Kind = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *ExternalSecretMappingDie) MetadataDie(fn func(d *v1.ObjectMetaDie)) *ExternalSecretMappingDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMapping) {
		d := v1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// SpecDie stamps the resource's spec field with a mutable die.
func (d *ExternalSecretMappingDie) SpecDie(fn func(d *ExternalSecretMappingSpecDie)) *ExternalSecretMappingDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMapping) {
		d := ExternalSecretMappingSpecBlank.DieImmutable(false).DieFeed(r.Spec)
		fn(d)
		r.Spec = d.DieRelease()
	})
}

// StatusDie stamps the resource's status field with a mutable die.
func (d *ExternalSecretMappingDie) StatusDie(fn func(d *ExternalSecretMappingStatusDie)) *ExternalSecretMappingDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMapping) {
		d := ExternalSecretMappingStatusBlank.DieImmutable(false).DieFeed(r.Status)
		fn(d)
		r.Status = d.DieRelease()
	})
}

func (d *ExternalSecretMappingDie) Spec(v v1alpha1.ExternalSecretMappingSpec) *ExternalSecretMappingDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMapping) {
		r.Spec = v
	})
}

func (d *ExternalSecretMappingDie) Status(v v1alpha1.ExternalSecretMappingStatus) *ExternalSecretMappingDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMapping) {
		r.Status = v
	})
}

var ExternalSecretMappingSpecBlank = (&ExternalSecretMappingSpecDie{}).DieFeed(v1alpha1.ExternalSecretMappingSpec{})

type ExternalSecretMappingSpecDie struct {
	mutable bool
	r       v1alpha1.ExternalSecretMappingSpec
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ExternalSecretMappingSpecDie) DieImmutable(immutable bool) *ExternalSecretMappingSpecDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ExternalSecretMappingSpecDie) DieFeed(r v1alpha1.ExternalSecretMappingSpec) *ExternalSecretMappingSpecDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ExternalSecretMappingSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ExternalSecretMappingSpecDie) DieFeedPtr(r *v1alpha1.ExternalSecretMappingSpec) *ExternalSecretMappingSpecDie {
	if r == nil {
		r = &v1alpha1.ExternalSecretMappingSpec{}
	}
	return d.DieFeed(*r)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension.
func (d *ExternalSecretMappingSpecDie) DieFeedRawExtension(raw runtime.RawExtension) *ExternalSecretMappingSpecDie {
	b, _ := json.Marshal(raw)
	r := v1alpha1.ExternalSecretMappingSpec{}
	_ = json.Unmarshal(b, &r)
	return d.DieFeed(r)
}

// DieRelease returns the resource managed by the die.
func (d *ExternalSecretMappingSpecDie) DieRelease() v1alpha1.ExternalSecretMappingSpec {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ExternalSecretMappingSpecDie) DieReleasePtr() *v1alpha1.ExternalSecretMappingSpec {
	r := d.DieRelease()
	return &r
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension.
func (d *ExternalSecretMappingSpecDie) DieReleaseRawExtension() runtime.RawExtension {
	r := d.DieReleasePtr()
	b, _ := json.Marshal(r)
	raw := runtime.RawExtension{}
	_ = json.Unmarshal(b, &raw)
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ExternalSecretMappingSpecDie) DieStamp(fn func(r *v1alpha1.ExternalSecretMappingSpec)) *ExternalSecretMappingSpecDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ExternalSecretMappingSpecDie) DeepCopy() *ExternalSecretMappingSpecDie {
	r := *d.r.DeepCopy()
	return &ExternalSecretMappingSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

var ExternalSecretMappingStatusBlank = (&ExternalSecretMappingStatusDie{}).DieFeed(v1alpha1.ExternalSecretMappingStatus{})

type ExternalSecretMappingStatusDie struct {
	mutable bool
	r       v1alpha1.ExternalSecretMappingStatus
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ExternalSecretMappingStatusDie) DieImmutable(immutable bool) *ExternalSecretMappingStatusDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ExternalSecretMappingStatusDie) DieFeed(r v1alpha1.ExternalSecretMappingStatus) *ExternalSecretMappingStatusDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ExternalSecretMappingStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ExternalSecretMappingStatusDie) DieFeedPtr(r *v1alpha1.ExternalSecretMappingStatus) *ExternalSecretMappingStatusDie {
	if r == nil {
		r = &v1alpha1.ExternalSecretMappingStatus{}
	}
	return d.DieFeed(*r)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension.
func (d *ExternalSecretMappingStatusDie) DieFeedRawExtension(raw runtime.RawExtension) *ExternalSecretMappingStatusDie {
	b, _ := json.Marshal(raw)
	r := v1alpha1.ExternalSecretMappingStatus{}
	_ = json.Unmarshal(b, &r)
	return d.DieFeed(r)
}

// DieRelease returns the resource managed by the die.
func (d *ExternalSecretMappingStatusDie) DieRelease() v1alpha1.ExternalSecretMappingStatus {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ExternalSecretMappingStatusDie) DieReleasePtr() *v1alpha1.ExternalSecretMappingStatus {
	r := d.DieRelease()
	return &r
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension.
func (d *ExternalSecretMappingStatusDie) DieReleaseRawExtension() runtime.RawExtension {
	r := d.DieReleasePtr()
	b, _ := json.Marshal(r)
	raw := runtime.RawExtension{}
	_ = json.Unmarshal(b, &raw)
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ExternalSecretMappingStatusDie) DieStamp(fn func(r *v1alpha1.ExternalSecretMappingStatus)) *ExternalSecretMappingStatusDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ExternalSecretMappingStatusDie) DeepCopy() *ExternalSecretMappingStatusDie {
	r := *d.r.DeepCopy()
	return &ExternalSecretMappingStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// ObservedGeneration is the 'Generation' of the mapping that was last processed by the controller.
func (d *ExternalSecretMappingStatusDie) ObservedGeneration(v int64) *ExternalSecretMappingStatusDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMappingStatus) {
		r.ObservedGeneration = v
	})
}

// Conditions are the conditions of this mapping
func (d *ExternalSecretMappingStatusDie) Conditions(v ...metav1.Condition) *ExternalSecretMappingStatusDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMappingStatus) {
		r.Conditions = v
	})
}

// Binding exposes the projected secret for this mapping
func (d *ExternalSecretMappingStatusDie) Binding(v *corev1.LocalObjectReference) *ExternalSecretMappingStatusDie {
	return d.DieStamp(func(r *v1alpha1.ExternalSecretMappingStatus) {
		r.Binding = v
	})
}
